### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by ilrein** [projectstorm/react-diagrams#150]
I am using a create-react-app alongside this notable library. I am able to load it just fine ordinarily, so I started working on adding unit tests. I noticed an immediate error (Jest/Enyzme):

```Test suite failed to run

    ReferenceError: Element is not defined
      
      at Object.n.__extends.Object.setPrototypeOf.__proto__ (node_modules/storm-react-diagrams/dist/main.js:1:37491)
      at __webpack_require__ (node_modules/storm-react-diagrams/dist/main.js:1:613)
      at Object.o (node_modules/storm-react-diagrams/dist/main.js:1:37222)
      at __webpack_require__ (node_modules/storm-react-diagrams/dist/main.js:1:613)
      at Object.n.__extends.Object.setPrototypeOf.__proto__ (node_modules/storm-react-diagrams/dist/main.js:1:14932)
      at __webpack_require__ (node_modules/storm-react-diagrams/dist/main.js:1:613)
      at Object.n.__extends.Object.setPrototypeOf.__proto__ (node_modules/storm-react-diagrams/dist/main.js:1:6833)
      at __webpack_require__ (node_modules/storm-react-diagrams/dist/main.js:1:613)
      at Object.n.__extends.Object.setPrototypeOf.__proto__ (node_modules/storm-react-diagrams/dist/main.js:1:3346)
      at __webpack_require__ (node_modules/storm-react-diagrams/dist/main.js:1:613)
```

Any thoughts on the issue?

**Comment by ilrein** [comment]
Looks like it was an issue with CRA setup. Just passing --env=jsdom to Jest removed this issue.
