### ISSUE TITLE
Extending PortModel causes Maximum call stack size exceeded with typescript@3.2.1

### ISSUE THREAD

**Issue by duvet86** [projectstorm/react-diagrams#307]
After upgrading to typescript 3.2.1 I started to get this:
```
RangeError: Maximum call stack size exceeded
    at resolveNameHelper (D:\NODEJS\workbench-ts\node_modules\typescript\lib\typescript.js:31831:35)
    at resolveName (D:\NODEJS\workbench-ts\node_modules\typescript\lib\typescript.js:31829:20)
    at resolveEntityName (D:\NODEJS\workbench-ts\node_modules\typescript\lib\typescript.js:32680:26)
    at resolveTypeReferenceName (D:\NODEJS\workbench-ts\node_modules\typescript\lib\typescript.js:38485:20)
    at getTypeFromTypeReference (D:\NODEJS\workbench-ts\node_modules\typescript\lib\typescript.js:38670:30)
    at getTypeFromTypeNode (D:\NODEJS\workbench-ts\node_modules\typescript\lib\typescript.js:40178:28)
    at getConstraintFromTypeParameter (D:\NODEJS\workbench-ts\node_modules\typescript\lib\typescript.js:38328:72)
    at fillMissingTypeArguments (D:\NODEJS\workbench-ts\node_modules\typescript\lib\typescript.js:37877:49)
    at getTypeFromClassOrInterfaceReference (D:\NODEJS\workbench-ts\node_modules\typescript\lib\typescript.js:38429:78)
    at getTypeReferenceTypeWorker (D:\NODEJS\workbench-ts\node_modules\typescript\lib\typescript.js:38559:24)
```

Investigating I found that it happens when I'm creating a class that extends from PortModel.
How to reproduce:
- Run this with typescript 3.2.1
```
import {
  LinkModel,
  DiagramEngine,
  PortModel,
  DefaultLinkModel
} from "storm-react-diagrams";

export class DiamondPortModel extends PortModel {
  public position: string | "top" | "bottom" | "left" | "right";

  constructor(pos: string = "top") {
    super(pos, "diamond");
    this.position = pos;
  }

  public serialize() {
    return Object.assign(super.serialize(), {
      position: this.position
    });
  }

  public deSerialize(data: any, engine: DiagramEngine) {
    super.deSerialize(data, engine);
    this.position = data.position;
  }

  public createLinkModel(): LinkModel {
    return new DefaultLinkModel();
  }
}
```
- Get the Maximum call stack size exceeded exception

Version:
"react": "^16.6.3",
"react-dom": "^16.6.3",
"storm-react-diagrams": "^5.2.1",
"typescript": "^3.2.1",

**Comment by duvet86** [comment]
After forking the project and updating few dependencies I found this in BaseEntity.ts
```
export interface BaseEvent<T extends BaseEntity = any> {
	entity: BaseEntity<BaseListener>;
	stopPropagation: () => any;
	firing: boolean;
	id: string;
}
```

`<T extends BaseEntity = any>`

The generic T is not used though and removing it fixes the infinite loop.
This is just to give you as much information as possible.

Let me know if I can help in any way.

Cheers.

**Comment by dylanvorster** [comment]
Should be fixed now in 6 beta, going to close for now
