### ISSUE TITLE
[window is not defined] Can this module be implemented for SSR?

### ISSUE THREAD

**Issue by dmytro-lymarenko** [projectstorm/react-diagrams#315]
I'm using next js and when I try to render it it gives me the error:
```
ReferenceError: window is not defined
    at Object.window (C:\Users\dlymarenko\source\Workspaces\BizBloqs\dev\BizBloqs.Management\BizBloqs.Management.Web.APP\node_modules\storm-react-diagrams\dist\webpack:\storm-react-diagrams\webpack\universalModuleDefinition:10:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\dlymarenko\source\Workspaces\BizBloqs\dev\BizBloqs.Management\BizBloqs.Management.Web.APP\node_modules\ts-node\src\index.ts:431:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module.patchedRequire [as require] (C:\Users\dlymarenko\source\Workspaces\BizBloqs\dev\BizBloqs.Management\BizBloqs.Management.Web.APP\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.storm-react-diagrams (webpack:/external "storm-react-diagrams":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 32c9115d350765cbd60f:21:0)
    at Object../pages/diagram/index.tsx (C:\Users\dlymarenko\source\Workspaces\BizBloqs\dev\BizBloqs.Management\BizBloqs.Management.Web.APP\build-client\server\bundles\pages\diagram.js:82:79)
    at __webpack_require__ (webpack:/webpack/bootstrap 32c9115d350765cbd60f:21:0)
    at Object.3 (C:\Users\dlymarenko\source\Workspaces\BizBloqs\dev\BizBloqs.Management\BizBloqs.Management.Web.APP\build-client\server\bundles\pages\diagram.js:187:18)
    at __webpack_require__ (webpack:/webpack/bootstrap 32c9115d350765cbd60f:21:0)
```

**Comment by vuvantoan95** [comment]
the same issue, help me!

**Comment by vuvantoan95** [comment]
fixed: https://stackoverflow.com/questions/52939439/dynamic-import-node-module-with-next-js

**Comment by dylanvorster** [comment]
While SSR is not officially supported, @vuvantoan95 is correct in stating that it should fix your issue
