### ISSUE TITLE
Unable to run diagrams-demo-project

### ISSUE THREAD

**Issue by slashwhatever** [projectstorm/react-diagrams#574]
run `yarn`
run `yarn start`

output: 

`
yarn run v1.22.4
$ ../../node_modules/.bin/webpack-dev-server
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:9000
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

This is on a freshly restarted machine with nothing running so I'm struggling to:
1. see what might be already on port 9000
2. change the port the demo project runs on

**Comment by renato-bohler** [comment]
Are you on Linux? Run this command and paste the output here: `netstat -ltnp | grep ':9000'`

**Comment by slashwhatever** [comment]
macOS

```
netstat: option requires an argument -- p
Usage:	netstat [-AaLlnW] [-f address_family | -p protocol]
	netstat [-gilns] [-f address_family]
	netstat -i | -I interface [-w wait] [-abdgRtS]
	netstat -s [-s] [-f address_family | -p protocol] [-w wait]
	netstat -i | -I interface -s [-f address_family | -p protocol]
	netstat -m [-m]
	netstat -r [-Aaln] [-f address_family]
	netstat -rs [-s]
```
