### ISSUE TITLE
Demo doesn't start

### ISSUE THREAD

**Issue by khpatel4991** [projectstorm/react-diagrams#679]
Hi,
I cloned this repo on my local, 
Ran `yarn install` and went to the gallery folder with `cd packages/diagrams-demo-gallery` and did `yarn run start` to start demo app as per the instructions.

I get the following error.

```
❯ yarn start                                                                                                                                                     98.113.168.5 ─╯
yarn run v1.22.4
$ ../../node_modules/.bin/start-storybook
internal/modules/cjs/loader.js:584
            if (e.code !== 'ERR_PACKAGE_PATH_NOT_EXPORTED') throw e;
                                                            ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "index.js" defined in the package config /Users/<myusername>/Code/react-diagrams/node_modules/is-promise/package.json; targets must start with "./"
    at resolveExportsTarget (internal/modules/cjs/loader.js:541:13)
    at resolveExportsTarget (internal/modules/cjs/loader.js:581:20)
    at applyExports (internal/modules/cjs/loader.js:454:14)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/kaspatel/Code/react-diagrams/node_modules/run-async/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
error Command failed with exit code 1.
```

```
Build Info
OS: Mac OS 10.15.4
Node Version: 12.18.2
```

**Comment by renato-bohler** [comment]
Try running `yarn build` on the project root folder.

**Comment by w8w8w8** [comment]
I run yarn install and yarn build on the project root folder.
then went to the gallery folder with cd packages/diagrams-demo-gallery and did yarn run start to start demo
and i get some error :

Uncaught TypeError: init is not a function
    at mountLazyComponent (vendors~main.manager.bundle.js:87950)
    at beginWork (vendors~main.manager.bundle.js:89343)
    at HTMLUnknownElement.callCallback (vendors~main.manager.bundle.js:74233)
    at Object.invokeGuardedCallbackDev (vendors~main.manager.bundle.js:74282)
    at invokeGuardedCallback (vendors~main.manager.bundle.js:74344)
    at beginWork$1 (vendors~main.manager.bundle.js:94247)
    at performUnitOfWork (vendors~main.manager.bundle.js:93062)
    at workLoopSync (vendors~main.manager.bundle.js:92990)
    at renderRootSync (vendors~main.manager.bundle.js:92953)
    at performSyncWorkOnRoot (vendors~main.manager.bundle.js:92576)

I NEED SOME HELP!!!!

**Comment by jonra1993** [comment]
Hello, @w8w8w8 I am facing the same issue. Did you solve it?

**Comment by w8w8w8** [comment]
> Hello, @w8w8w8 I am facing the same issue. Did you solve it?

no, I give up it
