### ISSUE TITLE
Rendering error with React Testing Library

### ISSUE THREAD

**Issue by zx-zheng** [projectstorm/react-diagrams#680]
I created app with create react app and it works well on browser. But tests with React Testing Library fails. How can I deal with this problem?

App.tsx
```typescript
import React from 'react';
import './App.css';
import createEngine, { DiagramModel, DefaultNodeModel } from '@projectstorm/react-diagrams';
import { CanvasWidget } from '@projectstorm/react-canvas-core';

function App() {
  var engine = createEngine();

  var model = new DiagramModel();

  var node1 = new DefaultNodeModel({
    name: 'Node 1',
    color: 'rgb(0,192,255)'
  });
  node1.setPosition(100, 100);

  model.addAll(node1);

  engine.setModel(model);
  return (
    <CanvasWidget className="dataflow-canvas" engine={engine} />
  );
}

export default App;
```

App.test.tsx
```typescript
import React from 'react';
import { render } from '@testing-library/react';
import App from './App';

test('renders without errors', () => {
  render(<App />);
});
```

Results.
```
 FAIL  src/App.test.tsx (6.013s)
  ✕ renders without errors (108ms)

  ● renders without errors

    TypeError: a.default is not a constructor

      4 | 
      5 | test('renders without errors', () => {
    > 6 |   render(<App />);
        |   ^
      7 | });
      8 | 

      at l.componentDidMount (node_modules/@projectstorm/react-diagrams-core/dist/webpack:/projectstorm/react-canvas-core/src/entities/node/NodeWidget.tsx:61:13)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19814:22)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22541:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at node_modules/react-dom/cjs/react-dom.development.js:24758:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24757:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24840:10)
      at node_modules/@testing-library/react/dist/pure.js:86:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at render (node_modules/@testing-library/react/dist/pure.js:82:26)
      at Object.<anonymous> (src/App.test.tsx:6:3)

  ● renders without errors

    TypeError: Cannot read property 'disconnect' of undefined

      4 | 
      5 | test('renders without errors', () => {
    > 6 |   render(<App />);
        |   ^
      7 | });
      8 | 

      at l.componentWillUnmount (node_modules/@projectstorm/react-diagrams-core/dist/webpack:/projectstorm/react-canvas-core/src/entities/node/NodeWidget.tsx:37:11)
      at callComponentWillUnmountWithTimer (node_modules/react-dom/cjs/react-dom.development.js:19580:12)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at safelyCallComponentWillUnmount (node_modules/react-dom/cjs/react-dom.development.js:19587:5)
      at commitUnmount (node_modules/react-dom/cjs/react-dom.development.js:20109:11)
      at commitNestedUnmounts (node_modules/react-dom/cjs/react-dom.development.js:20163:5)
      at unmountHostComponents (node_modules/react-dom/cjs/react-dom.development.js:20443:7)
      at commitDeletion (node_modules/react-dom/cjs/react-dom.development.js:20500:5)
      at commitMutationEffects (node_modules/react-dom/cjs/react-dom.development.js:22782:11)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22509:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at node_modules/react-dom/cjs/react-dom.development.js:11089:24
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11084:7)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11072:3)
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21862:7)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at render (node_modules/@testing-library/react/dist/pure.js:82:26)
      at Object.<anonymous> (src/App.test.tsx:6:3)
```

package.json
```json
{
  "name": "diagrams-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/core": "^10.0.28",
    "@emotion/styled": "^10.0.27",
    "@projectstorm/react-diagrams": "^6.2.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "@types/jest": "^24.9.1",
    "@types/node": "^12.12.50",
    "@types/react": "^16.9.43",
    "@types/react-dom": "^16.9.8",
    "closest": "^0.0.1",
    "dagre": "^0.8.5",
    "lodash": "^4.17.19",
    "ml-matrix": "^6.5.0",
    "pathfinding": "^0.4.18",
    "paths-js": "^0.4.10",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "resize-observer-polyfill": "^1.5.1",
    "typescript": "^3.9.7"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by renato-bohler** [comment]
I've had issues running tests when there is some node added by default. You can try without adding nodes to see if it works... but this definetely needs to be fixed, as it makes testing basically impracticable.

**Comment by zx-zheng** [comment]
Mocking `resize-observer-polyfill` as following solved problem.

```typescript
import React from 'react';
import { render } from '@testing-library/react';
import App from './App';

jest.mock('resize-observer-polyfill', () => {
  return {
    default: jest.fn().mockImplementation(() => {
      return {
        constructor: () => { },
        disconnect: () => { },
        observe: () => { }
      }
    })
  }
})

test('renders without errors', () => {
  render(<App />);
});
```

reference: https://stackoverflow.com/a/56690970
